#!/usr/bin/env bash

# git-add-files
# license: GPL-2.0-only
# (c) 2024 Kipras Melnikovas

set -euo pipefail

CONFIG_DISABLE_INFO="addfiles.noInfoComment"
CONFIG_ABBREV_COMMANDS="addfiles.abbreviateCommands"

FILENAME="ADD_FILES"

CMD_ADD="add"
CMD_WIP="wip"
CMD_STAGED="staged"
CMD_HALFSTAGED="halfstaged"
CMD_EDIT="edit"

SHORT_CMD_ADD="a"
SHORT_CMD_WIP="w"
SHORT_CMD_STAGED="s"
SHORT_CMD_HALFSTAGED="h"
SHORT_CMD_EDIT="e"

INFO_MSG="\
# delete \"$CMD_ADD\"    lines to prevent  files from getting staged.
# delete \"$CMD_STAGED\" lines to un-stage files.
#
# change \"$CMD_ADD\"    to \"$CMD_EDIT\" to selectively    stage parts of file
# change \"$CMD_STAGED\" to \"$CMD_EDIT\" to selectively un-stage parts of file
#
# delete \"$CMD_HALFSTAGED\" (noop) lines to un-stage partially-staged files.
# change \"$CMD_HALFSTAGED\" (noop) to \"$CMD_ADD\" to stage partially-staged files.
#
# \"wip\" is noop, cached in .git/add-files/wip
#
# all commands have a single-char shortcut.
# empty lines and lines starting with '#' will be ignored.
# to abort, exit with non-0 code (e.g. :cq in vim).
# vim: ft=gitaddfiles
"

USAGE="\
usage:
$ git-add-files
$ git-add-files -h
"
git_add_files__parse_argv() {
	test $# -gt 0 || return 0

	case "$1" in
		-h|--help)
			printf "%s" "$USAGE"
			exit 0
			;;
		*)
			printf "%s\nunknown arg '%s'\n" "$USAGE" "$1"
			exit 1
			;;
	esac
}

git_add_files() {
	msg() {
		FMT="$1"
		shift
		# shellcheck disable=2059
		>&2 printf "$FMT" "$@"
	}
	die() {
		msg "$1"
		exit "${2:-1}"
	}
	BUG() {
		msg="$1"
		shift
		die "BUG: $msg" "$@"
	}

	git_add_files__parse_argv "$@"

	EDITOR="${EDITOR:-vi}"

	repodir="$(git rev-parse --show-toplevel)"
	gitdir="$(git rev-parse --git-dir)"

	FILE_STORE="$gitdir/add-files"
	file="$gitdir/$FILENAME"
	FILE_WIP="$FILE_STORE/wip"

	mkdir -p "$FILE_STORE"

	COMMENT_REGEX="\s*#.*$"

	# TODO: save to files, instead of holding in variables
	# TODO: keep files in .git/addfiles/

	# TODO: lowercase variable names unless global

	# TODO: halfstaged
	#git status --porcelain=v1

	ADD="$(   git diff --stat          | head -n -1 | sed "s@^ @@g; s@|@ #@g; s@$COMMENT_REGEX@@g")"
	STAGED="$(git diff --stat --staged | head -n -1 | sed "s@^ @@g; s@|@ #@g; s@$COMMENT_REGEX@@g")"

	inject_prefix_into() {
		test $# -eq 2 || BUG "inject_prefix_into requires 2 args\n"
		printf "%s" "$1" | sed "s@^@$2@g"
	}

	if test -f "$FILE_WIP"; then
		ADD_WITHOUT_WIP="$(printf "%b" "$ADD" | { grep -vFf "$FILE_WIP" ||: ; })"
		WIP="$(printf "%b" "$ADD" | { grep -Ff "$FILE_WIP" ||: ; })"
	else
		ADD_WITHOUT_WIP="$ADD"
		WIP=""
	fi

	if test "$(git config "$CONFIG_ABBREV_COMMANDS")" = "true"; then
		ADD_READY="$(inject_prefix_into "$ADD_WITHOUT_WIP" "$SHORT_CMD_ADD ")"
		WIP_READY="$(inject_prefix_into "$WIP" "$SHORT_CMD_WIP ")"
		STAGED_READY="$(inject_prefix_into "$STAGED" "$SHORT_CMD_STAGED ")"
	else
		ADD_READY="$(inject_prefix_into "$ADD_WITHOUT_WIP" "$CMD_ADD ")"
		WIP_READY="$(inject_prefix_into "$WIP" "$CMD_WIP ")"
		STAGED_READY="$(inject_prefix_into "$STAGED" "$CMD_STAGED ")"
	fi

	sep1=""
	sep2=""
	test -n "$ADD_READY" && test -n "$WIP_READY" && sep1="\n\n"
	test -n "$WIP_READY" && test -n "$STAGED_READY" && sep2="\n\n"
	printf "%s%b%s%b%s\n%s" "$ADD_READY" "$sep1" "$WIP_READY" "$sep2" "$STAGED_READY" > "$file"

	test "$(git config "$CONFIG_DISABLE_INFO")" != "true" && {
		printf "\n%s" "$INFO_MSG" >> "$file"
	}

	msg "hint: Waiting for your editor to close the file... "
	$EDITOR "$file" || {
		msg "error: There was a problem with the editor '%s'.\n" "$EDITOR"
		die "" $?
	}
	msg "\n"

	file1="/tmp/${FILENAME}.1"
	file1uniq="${file1}u"
	# remove comments and empty lines
	sed "/^\s*$/d; /^#/d; s@$COMMENT_REGEX@@g" "$file" | sort > "$file1"
	uniq "$file1" > "$file1uniq"

	diff --minimal "$file1" "$file1uniq" | { grep '^<' ||: ; } || {
		die "fatal: duplicate filepaths found\n"
	}

	line_head() {
		printf "%s" "$1" | cut -d' ' -f1
	}
	line_tail() {
		printf "%s" "$1" | cut -d' ' -f2
	}
	validate_file() {
		# TODO handle deletions

		# TODO handle submodule "files" which are directories,
		# and cannot be added if include uncommitted changes.

		test -f "$1" || test -d "$1" || msg "file does not exit '$1'\n"
	}

	marked_added="/tmp/marked_added"
	marked_staged="/tmp/marked_staged"
	marked_wip="/tmp/marked_wip"
	marked_edit="/tmp/marked_edit"
	test -f "$marked_added"  && mv -f "$marked_added"  "$marked_added.prev"
	test -f "$marked_staged" && mv -f "$marked_staged" "$marked_staged.prev"
	test -f "$marked_wip" && mv -f "$marked_wip" "$marked_wip.prev"
	test -f "$marked_edit" && mv -f "$marked_edit" "$marked_edit.prev"
	touch "$marked_added"
	touch "$marked_staged"
	touch "$marked_wip"
	touch "$marked_edit"
	had_adds=0

	# process & validate lines, group filepaths.
	# no side-effects on git repo yet.
	while read -r line; do
		case "$line" in
			"$CMD_ADD"|"$SHORT_CMD_ADD"*)
				rest="$(line_tail "$line")"
				file="$(line_head "$rest")"
				filepath="$(realpath "$repodir/$file")"

				validate_file "$filepath"

				printf "%s\n" "$file" >> "$marked_added"
				had_adds=1
				;;
			"$CMD_WIP"|"$SHORT_CMD_WIP"*)
				rest="$(line_tail "$line")"
				file="$(line_head "$rest")"
				filepath="$(realpath "$repodir/$file")"

				validate_file "$filepath"

				printf "%s\n" "$file" >> "$marked_wip"
				;;
			"$CMD_STAGED"|"$SHORT_CMD_STAGED"*)
				rest="$(line_tail "$line")"
				file="$(line_head "$rest")"
				filepath="$(realpath "$repodir/$file")"

				validate_file "$filepath"

				printf "%s\n" "$file" >> "$marked_staged"
				;;
			"$CMD_HALFSTAGED"|"$SHORT_CMD_HALFSTAGED"*)
				# noop
				;;
			"$CMD_EDIT"|"$SHORT_CMD_EDIT"*)
				rest="$(line_tail "$line")"
				file="$(line_head "$rest")"
				filepath="$(realpath "$repodir/$file")"

				validate_file "$filepath"

				printf "%s\n" "$file" >> "$marked_edit"
				;;
			*)
				die "fatal: unknown command in line '$line'\n"
				;;
		esac
	done < "$file1"

	# add all lines that were kept as "add"

	# TODO refactor abs
	var_marked_added="$(inject_prefix_into "$(cat "$marked_added")" "$repodir/")"
	marked_added_abs="/tmp/marked_added_abs"
	printf "%s" "$var_marked_added" > "$marked_added_abs"
	test "$had_adds" -eq 0 || git add --pathspec-from-file="$marked_added_abs"

	# unstage if any "staged" lines were removed

	were_staged="/tmp/were_staged"
	printf "%s" "$STAGED" > "$were_staged"
	trim_trailing_newline "$were_staged"

	delta_staged="/tmp/delta_staged"

	diff --minimal "$were_staged" "$marked_staged" > "$delta_staged" || {
		grep "^>" "$delta_staged" && {
			die "fatal: you marked non-staged files as staged?\n"
		}

		unmarked_staged="/tmp/unmarked_staged"
		grep "^<" "$delta_staged" | sed 's@^< @@g' > "$unmarked_staged"

		# convert to absolute filepaths,
		# for --pathspec-from-file to work
		# TODO refactor abs
		var_unmarked_staged="$(cat "$unmarked_staged")"
		var_unmarked_staged_abs="$(inject_prefix_into "$var_unmarked_staged" "$repodir/")"
		unmarked_staged_abs="/tmp/unmarked_staged_abs"
		printf "%s" "$var_unmarked_staged_abs" > "$unmarked_staged_abs"

		git reset --pathspec-from-file="$unmarked_staged_abs" HEAD
	}

	# mark all lines as "wip" that have removed "add"

	were_to_be_added="/tmp/were_to_be_added"
	printf "%s" "$ADD" > "$were_to_be_added"
	trim_trailing_newline "$were_to_be_added"

	delta_add="/tmp/delta_add"
	diff --minimal "$were_to_be_added" "$marked_added" > "$delta_add" || {
		unmarked_add="/tmp/unmarked_add"
		grep "^<" "$delta_add" | sed 's@^< @@g' > "$unmarked_add"

		cat "$unmarked_add" "$marked_wip" | sort | uniq > "$FILE_WIP"
	}

	# launch interactive 'add -p' for lines that were marked as "edit"

	# TODO
}

trim_trailing_newline() {
	file="$1"
	shift
	cat "$file" | perl -pe 'chomp if eof' > "$file.tmp"
	mv -f "$file.tmp" "$file"
}

git_add_files "$@"

